id: P007103
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 12:41:49.803342
source_metadata:
  id: bdr:W1KG1085
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་ཚིག་ལེའུར་བྱས་པ་ཞེས་བྱ་བའི་མཆན་འགྲེལ་
  author: ''
  volumes:
    0a23e5ce37724c42aaa06905bf37bd89:
      image_group_id: I1KG1093
      title: Volume 1 of tshad ma rnam 'grel gyi tshig le'ur byas pa zhes bya ba'i
        mchan 'grel
      volume_number: 1
      total_pages: 528
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
