id: P007103
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG1085
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་ཚིག་ལེའུར་བྱས་པ་ཞེས་བྱ་བའི་མཆན་འགྲེལ་
  author: ''
  volumes:
    a86cc9706a7c44dfbb4480426012ba9e:
      image_group_id: I1KG1093
      title: ''
      volume_number: 1
      total_pages: 528
ebook_metadata:
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་ཚིག་ལེའུར་བྱས་པ་ཞེས་བྱ་བའི་མཆན་འགྲེལ་
  author: ''
  sku: P007103
  cover: cover.jpg
  layers:
  - pagination
