id: I6A4535BA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T11:22:56+00:00'
last_modified: '2022-06-09T04:55:13.319614+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1085
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་ཚིག་ལེའུར་བྱས་པ་ཞེས་བྱ་བའི་མཆན་འགྲེལ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    898F:
      image_group_id: I1KG1093
      title: Volume 1 of tshad ma rnam 'grel gyi tshig le'ur byas pa zhes bya ba'i
        mchan 'grel
      total_pages: 528
      order: 1
      base_file: 898F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
